import DDNNFNegation.RestrictedEncoder
import TutorialBox

/-!
# The image of a restricted encoder

The partial sums form the subgroup generated by the selected columns.
Viewing the alphabet as a vector space over the two-element field relates
this subgroup's index to the codimension of their span. These identities
connect the probabilistic encoder construction to the image-size and
fiber bounds used for balanced partitions.
-/

namespace DDNNFNegation

open Finset Module

/-- Adjoining one vector to an addition-closed set leaves its size unchanged
if the vector is already present, and doubles its size otherwise. -/
@[tutorial_box "lem:tutorial-output-doubling"]
theorem adjoining_vector_size {G : Type*} [AddCommGroup G] [DecidableEq G]
    (hexp : ∀ g : G, g + g = 0) (B : Finset G)
    (hclosed : ∀ a ∈ B, ∀ b ∈ B, a + b ∈ B) (g : G) :
    (B ∪ B.image (fun b => b + g)).card =
      if g ∈ B then B.card else 2 * B.card := by
  by_cases hg : g ∈ B
  · rw [if_pos hg]
    have hsub : B.image (fun b => b + g) ⊆ B := by
      intro b hb
      obtain ⟨a, ha, rfl⟩ := mem_image.mp hb
      exact hclosed a ha g hg
    rw [union_eq_left.mpr hsub]
  · rw [if_neg hg]
    have hd : Disjoint B (B.image (fun b => b + g)) := by
      apply disjoint_left.mpr
      intro b hb himage
      obtain ⟨a, ha, heq⟩ := mem_image.mp himage
      have hga : g = a + b := by
        calc g = a + (a + g) := by rw [← add_assoc, hexp, zero_add]
             _ = a + b := by rw [heq]
      exact hg (hga ▸ hclosed a ha b hb)
    rw [card_union_of_disjoint hd,
      card_image_of_injective B (fun a b h => add_right_cancel h)]
    omega

/-! ### The span of the columns -/

section Span

variable {ι G : Type*} [AddCommGroup G] [Module (ZMod 2) G]

/-- The tutorial's image `im(E_J)`, represented as the binary-linear span
of the selected columns. -/
noncomputable def columnSpan (a : ι → G) (S : Finset ι) : Submodule (ZMod 2) G :=
  Submodule.span (ZMod 2) (a '' (S : Set ι))

/-- Over `𝔽₂` the span of the columns is the subgroup they generate. -/
theorem columnSpan_toAddSubgroup (a : ι → G) (S : Finset ι) :
    (columnSpan a S).toAddSubgroup = partialImage a S := by
  apply le_antisymm
  · intro x hx
    have hle : columnSpan a S ≤
        AddSubgroup.toZModSubmodule 2 (partialImage a S) :=
      Submodule.span_le.mpr (fun y hy => AddSubgroup.subset_closure hy)
    exact hle hx
  · exact (AddSubgroup.closure_le _).mpr (by
      rw [Submodule.coe_toAddSubgroup]
      exact Submodule.subset_span)

/-- Changing from the additive subgroup to its binary-linear span preserves the number of
outputs. -/
theorem natCard_generatedByColumns (a : ι → G) (S : Finset ι) :
    Nat.card (partialImage a S) = Nat.card (columnSpan a S) := by
  rw [← columnSpan_toAddSubgroup]
  rfl

end Span

/-! ### The index is a power of two -/

section Index

variable {ι G : Type*} [AddCommGroup G] [Module (ZMod 2) G] [Finite G]

/-- An `𝔽₂`-space of dimension `d` has `2^d` elements. -/
theorem natCard_eq_two_pow_finrank (V : Type*) [AddCommGroup V] [Module (ZMod 2) V]
    [Finite V] : Nat.card V = 2 ^ finrank (ZMod 2) V := by
  rw [Module.natCard_eq_pow_finrank (K := ZMod 2) (V := V), Nat.card_zmod]

omit [Finite G] in
/-- `[G : G_S] · |G_S| = |G|`: the cosets of `G_S` partition `G`. -/
theorem index_mul_natCard_columnSpan (a : ι → G) (S : Finset ι) :
    Nat.card (G ⧸ partialImage a S) * Nat.card (columnSpan a S) = Nat.card G := by
  rw [← natCard_generatedByColumns, ← AddSubgroup.index_eq_card]
  exact AddSubgroup.index_mul_card _

/-- Internal index form of the tutorial's power-of-two image-size fact. -/
theorem index_eq_two_pow (a : ι → G) (S : Finset ι) :
    Nat.card (G ⧸ partialImage a S) =
      2 ^ (finrank (ZMod 2) G - finrank (ZMod 2) (columnSpan a S)) := by
  have h := index_mul_natCard_columnSpan a S
  rw [natCard_eq_two_pow_finrank G, natCard_eq_two_pow_finrank (columnSpan a S)] at h
  have hle : finrank (ZMod 2) (columnSpan a S) ≤ finrank (ZMod 2) G :=
    Submodule.finrank_le _
  have hpos : 0 < 2 ^ finrank (ZMod 2) (columnSpan a S) := by positivity
  apply Nat.eq_of_mul_eq_mul_right hpos
  rw [h, ← pow_add, Nat.sub_add_cancel hle]

/-- `[G : G_S] > 8` forces `dim G_S ≤ dim G - 4`. -/
theorem finrank_add_four_le_of_index_gt_eight (a : ι → G) (S : Finset ι)
    (h8 : 8 < Nat.card (G ⧸ partialImage a S)) :
    finrank (ZMod 2) (columnSpan a S) + 4 ≤ finrank (ZMod 2) G := by
  rw [index_eq_two_pow] at h8
  have hle : finrank (ZMod 2) (columnSpan a S) ≤ finrank (ZMod 2) G :=
    Submodule.finrank_le _
  have h4 : 4 ≤ finrank (ZMod 2) G - finrank (ZMod 2) (columnSpan a S) := by
    by_contra hlt
    push Not at hlt
    have : 2 ^ (finrank (ZMod 2) G - finrank (ZMod 2) (columnSpan a S)) ≤ 2 ^ 3 :=
      Nat.pow_le_pow_right (by norm_num) (by omega)
    omega
  omega

end Index

/-! ### Extending to a subspace of codimension four -/

section Extension

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V] [FiniteDimensional K V]

/-- Enlarge a subspace one vector at a time until it has the target
dimension. Over the binary field, each dimension increase doubles its size;
this implements the tutorial's construction of a containing set. -/
theorem exists_superspace_of_finrank (W : Submodule K V) (m : ℕ)
    (hW : finrank K W ≤ m) (hm : m ≤ finrank K V) :
    ∃ H : Submodule K V, W ≤ H ∧ finrank K H = m := by
  revert hm
  induction m, hW using Nat.le_induction with
  | base =>
    intro _
    exact ⟨W, le_rfl, rfl⟩
  | succ m _ ih =>
    intro hm
    obtain ⟨H, hWH, hH⟩ := ih (by omega)
    have hne : H ≠ ⊤ := by
      intro htop
      rw [htop, finrank_top] at hH
      omega
    obtain ⟨v, -, hv⟩ := SetLike.exists_of_lt (lt_top_iff_ne_top.mpr hne)
    have hv0 : v ≠ 0 := fun h0 => hv (h0 ▸ H.zero_mem)
    refine ⟨H ⊔ Submodule.span K {v}, hWH.trans le_sup_left, ?_⟩
    have hsum := Submodule.finrank_sup_add_finrank_inf_eq H (Submodule.span K {v})
    have hinf : H ⊓ Submodule.span K {v} = ⊥ :=
      ((Submodule.disjoint_span_singleton' hv0).mpr hv).eq_bot
    rw [hinf, finrank_bot, add_zero, finrank_span_singleton hv0, hH] at hsum
    exact hsum

end Extension

/-- A small image is contained in an output set of exactly `|G|/16`
elements, obtained by adjoining vectors outside the current set. -/
theorem exists_containing_set_of_small_image
    {ι G : Type*} [AddCommGroup G] [Module (ZMod 2) G] [Finite G]
    (m : ℕ) (hdim : finrank (ZMod 2) G = 4 * m)
    (a : ι → G) (J : Finset ι) (h8 : 8 < Nat.card (G ⧸ partialImage a J)) :
    ∃ H : Submodule (ZMod 2) G,
      (∀ j ∈ J, a j ∈ H) ∧ finrank (ZMod 2) H = 4 * m - 4 := by
  have hsmall := finrank_add_four_le_of_index_gt_eight a J h8
  obtain ⟨H, hJH, hH⟩ := exists_superspace_of_finrank (columnSpan a J)
    (4 * m - 4) (by omega) (by omega)
  exact ⟨H, fun j hj => hJH (Submodule.subset_span ⟨j, hj, rfl⟩), hH⟩

end DDNNFNegation
