import DDNNFNegation.RestrictedEncoder
import TutorialBox

/-!
# Equal fibers of the encoder

The partial-sum map on a set of positions is a homomorphism onto the
subgroup generated by the selected columns. Translation gives bijections
between its fibers. Thus every point of the image has the same number of
preimages, and the fiber size times the image size is the number of
assignments to those positions.
-/

namespace DDNNFNegation

open Finset

variable {ι G : Type*} [DecidableEq ι] [AddCommGroup G]

omit [DecidableEq ι] in
/-- `E_J` is additive, `E_J(x ⊕ y) = E_J(x) + E_J(y)`, because a column
selected twice contributes `a i + a i = 0`. -/
theorem partialSubsetSum_xor (hexp : ∀ g : G, g + g = 0) (a : ι → G) (S : Finset ι)
    (x y : S → Bool) :
    partialSubsetSum a S (fun i => xor (x i) (y i)) =
      partialSubsetSum a S x + partialSubsetSum a S y := by
  unfold partialSubsetSum
  rw [← sum_add_distrib]
  apply sum_congr rfl
  intro i _
  cases hx : x i <;> cases hy : y i <;> simp [hx, hy, hexp (a i)]

/-- Every element of the subgroup generated by the selected columns is a partial sum of those columns. -/
theorem exists_partialSubsetSum_eq (hexp : ∀ g : G, g + g = 0) (a : ι → G) (S : Finset ι)
    {z : G} (hz : z ∈ partialImage a S) :
    ∃ x : S → Bool, partialSubsetSum a S x = z := by
  unfold partialImage at hz
  refine AddSubgroup.closure_induction ?_ ?_ ?_ ?_ hz
  · rintro g ⟨i, hi, rfl⟩
    have hiS : i ∈ S := by simpa using hi
    refine ⟨fun j => decide ((j : ι) = i), ?_⟩
    unfold partialSubsetSum
    rw [sum_attach S (fun k => if decide (k = i) = true then a k else 0)]
    simp only [decide_eq_true_eq]
    rw [sum_ite_eq' S i a]
    exact if_pos hiS
  · exact ⟨fun _ => false, by simp [partialSubsetSum]⟩
  · rintro g h _ _ ⟨x, hx⟩ ⟨y, hy⟩
    exact ⟨fun i => xor (x i) (y i), by rw [partialSubsetSum_xor hexp, hx, hy]⟩
  · rintro g _ ⟨x, hx⟩
    exact ⟨x, by rw [hx, neg_eq_of_add_eq_zero_right (hexp g)]⟩

variable [DecidableEq G]

/-- The fibers of `E_J` over any two points `z, t` of `im(E_J)` have the same
size. With `E_J(x₀) = z + t`, the translation `x ↦ x ⊕ x₀` is its own
inverse and exchanges the two fibers. -/
theorem card_finiteMapFiber_eq_of_mem (hexp : ∀ g : G, g + g = 0) (a : ι → G) (S : Finset ι)
    {z t : G} (hz : z ∈ partialImage a S) (ht : t ∈ partialImage a S) :
    (finiteMapFiber (partialSubsetSum a S) z).card =
      (finiteMapFiber (partialSubsetSum a S) t).card := by
  obtain ⟨x₀, hx₀⟩ := exists_partialSubsetSum_eq hexp a S ((partialImage a S).add_mem hz ht)
  have translate : ∀ {u v : G} (x : S → Bool), u + v = partialSubsetSum a S x₀ →
      partialSubsetSum a S x = u → partialSubsetSum a S (fun i => xor (x i) (x₀ i)) = v := by
    intro u v x huv hx
    rw [partialSubsetSum_xor hexp, hx, ← huv, ← add_assoc, hexp, zero_add]
  apply card_nbij' (fun x => fun i => xor (x i) (x₀ i)) (fun x => fun i => xor (x i) (x₀ i))
  · intro x hx
    simp only [finiteMapFiber, mem_coe, mem_filter, mem_univ, true_and] at hx ⊢
    exact translate x hx₀.symm hx
  · intro x hx
    simp only [finiteMapFiber, mem_coe, mem_filter, mem_univ, true_and] at hx ⊢
    exact translate x (by rw [hx₀, add_comm]) hx
  · intro x _
    funext i
    simp
  · intro x _
    funext i
    simp

/-- The fiber over a point outside `im(E_J)` is empty. -/
theorem finiteMapFiber_eq_empty_of_not_mem (a : ι → G) (S : Finset ι) {z : G}
    (hz : z ∉ partialImage a S) :
    finiteMapFiber (partialSubsetSum a S) z = ∅ := by
  apply filter_eq_empty_iff.mpr
  intro x _ hx
  exact hz (hx ▸ partialSubsetSum_mem_partialImage a S x)

variable [Fintype G]

/-- Exact uniformity: for `z ∈ im(E_J)`, `|E_J⁻¹(z)| · |im(E_J)| = 2^{|J|}`, since
the `2^{|J|}` assignments are partitioned by their partial sum into `|im(E_J)|`
fibers of equal size. -/
@[tutorial_box "lem:tutorial-encoder-fibers"]
theorem equal_fiber_sizes (hexp : ∀ g : G, g + g = 0) (a : ι → G)
    (S : Finset ι) {z : G} (hz : z ∈ partialImage a S) :
    (finiteMapFiber (partialSubsetSum a S) z).card * Nat.card (partialImage a S) =
      2 ^ S.card := by
  classical
  have hcard : Nat.card (partialImage a S) = (univ.filter (· ∈ partialImage a S)).card := by
    rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
  calc (finiteMapFiber (partialSubsetSum a S) z).card * Nat.card (partialImage a S)
      = ∑ t ∈ univ.filter (· ∈ partialImage a S),
          (finiteMapFiber (partialSubsetSum a S) t).card := by
        rw [hcard, sum_congr rfl fun t ht =>
          card_finiteMapFiber_eq_of_mem hexp a S (mem_filter.mp ht).2 hz, sum_const,
          smul_eq_mul, mul_comm]
    _ = ∑ t, (finiteMapFiber (partialSubsetSum a S) t).card := by
        apply sum_subset (subset_univ _)
        intro t _ ht
        rw [finiteMapFiber_eq_empty_of_not_mem a S
          fun h => ht (mem_filter.mpr ⟨mem_univ _, h⟩), card_empty]
    _ = (univ : Finset (S → Bool)).card := by
        unfold finiteMapFiber
        exact (card_eq_sum_card_fiberwise fun x _ => mem_univ (partialSubsetSum a S x)).symm
    _ = 2 ^ S.card := by
        rw [card_univ, Fintype.card_fun, Fintype.card_bool, Fintype.card_coe]

/-- Over every point `z`, the fiber has size at most `2^{|J|} / |im(E_J)|`, expressed over the reals. -/
theorem card_finiteMapFiber_le_div (hexp : ∀ g : G, g + g = 0) (a : ι → G) (S : Finset ι)
    (z : G) :
    ((finiteMapFiber (partialSubsetSum a S) z).card : ℝ) ≤
      2 ^ S.card / Nat.card (partialImage a S) := by
  have hpos : (0 : ℝ) < Nat.card (partialImage a S) := by exact_mod_cast Nat.card_pos
  rw [le_div_iff₀ hpos]
  by_cases hz : z ∈ partialImage a S
  · exact_mod_cast (equal_fiber_sizes hexp a S hz).le
  · rw [finiteMapFiber_eq_empty_of_not_mem a S hz, card_empty, Nat.cast_zero, zero_mul]
    positivity

end DDNNFNegation
