import DDNNFNegation.Encoder
import DDNNFNegation.Rectangles
import TutorialBox

/-!
# Restricting the encoder to a set of positions

Assignments outside the selected positions are fixed to zero. The resulting
partial-sum map has image equal to the subgroup generated by those columns.
The fiber identities apply both to this restricted map and to the full
encoder.
-/

namespace DDNNFNegation

open Finset

variable {ι G : Type*} [Fintype ι] [DecidableEq ι]

/-- The tutorial's restricted encoder `E_J`: multiplication by the columns
at the selected positions (the internal position set is named `S`). -/
@[tutorial_box "def:tutorial-restricted-encoder"]
def partialSubsetSum [AddCommMonoid G] (a : ι → G) (S : Finset ι) (x : S → Bool) : G :=
  ∑ i ∈ S.attach, if x i then a i else 0

/-- The tutorial's `im(E_J)`, represented by the subgroup generated by the
selected columns. Over the binary space, `exists_partialSubsetSum_eq` proves
that these are exactly the outputs of the restricted encoder. -/
@[tutorial_box "def:tutorial-restricted-encoder"]
noncomputable def partialImage [AddCommGroup G] (a : ι → G) (S : Finset ι) : AddSubgroup G :=
  AddSubgroup.closure (a '' (S : Set ι))

/-- The tutorial's fiber `E_J⁻¹(t)` over an output `t`, the assignments that
produce that sum: the complete finite fiber of a map, defined for any map
with a finite domain and used at `partialSubsetSum a S` (the encoder lemma)
and at `subsetSum a` (the zero fiber). -/
@[tutorial_box "def:tutorial-encoder-fibers"]
def finiteMapFiber {X Z : Type*} [Fintype X] [DecidableEq X] [DecidableEq Z]
    (f : X → Z) (z : Z) : Finset X :=
  univ.filter fun x => f x = z

omit [Fintype ι] [DecidableEq ι] in
/-- Every restricted encoder output lies in `im(E_J)`: each selected column
is a generator. -/
theorem partialSubsetSum_mem_partialImage [AddCommGroup G] (a : ι → G) (S : Finset ι)
    (x : S → Bool) : partialSubsetSum a S x ∈ partialImage a S := by
  unfold partialSubsetSum partialImage
  refine AddSubgroup.sum_mem _ fun i _ => ?_
  split_ifs
  · exact AddSubgroup.subset_closure ⟨i, i.property, rfl⟩
  · exact AddSubgroup.zero_mem _

/-- At a cut `J`, `Ex = E_J x_J + E_{Jᶜ} x_{Jᶜ}`. -/
theorem subsetSum_partition [AddCommMonoid G] (a : ι → G) (S : Finset ι) (x : ι → Bool) :
    subsetSum a x = partialSubsetSum a S (fun i => x i) + partialSubsetSum a Sᶜ (fun i => x i) := by
  unfold subsetSum partialSubsetSum
  rw [← sum_add_sum_compl S, sum_attach S (fun i => if x i then a i else 0),
    sum_attach Sᶜ (fun i => if x i then a i else 0)]

/-- The same split for an assignment given by its two restrictions. -/
theorem subsetSum_partition_symm [AddCommMonoid G] (a : ι → G) (S : Finset ι)
    (p : (S → Bool) × (↥(Sᶜ) → Bool)) :
    subsetSum a ((assignmentPartitionEquiv S).symm p) =
      partialSubsetSum a S p.1 + partialSubsetSum a Sᶜ p.2 := by
  rw [subsetSum_partition a S]
  exact congrArg (fun q : (S → Bool) × (↥(Sᶜ) → Bool) =>
    partialSubsetSum a S q.1 + partialSubsetSum a Sᶜ q.2)
    ((assignmentPartitionEquiv S).apply_symm_apply p)

/-- The final arithmetic of the rectangle estimate: two images each of
size at least `|G|/8` give a ratio at most `64`. -/
theorem two_index_bound [Fintype G] [AddCommGroup G] (H K : AddSubgroup G)
    (hH : Fintype.card G ≤ 8 * Nat.card H) (hK : Fintype.card G ≤ 8 * Nat.card K) :
    (Fintype.card G : ℝ) ^ 2 / ((Nat.card H : ℝ) * Nat.card K) ≤ 64 := by
  have hHpos : (0 : ℝ) < Nat.card H := by exact_mod_cast (Nat.card_pos : 0 < Nat.card H)
  have hKpos : (0 : ℝ) < Nat.card K := by exact_mod_cast (Nat.card_pos : 0 < Nat.card K)
  have hH' : (Fintype.card G : ℝ) ≤ 8 * Nat.card H := by exact_mod_cast hH
  have hK' : (Fintype.card G : ℝ) ≤ 8 * Nat.card K := by exact_mod_cast hK
  rw [div_le_iff₀ (mul_pos hHpos hKpos), sq]
  calc (Fintype.card G : ℝ) * Fintype.card G ≤ (8 * Nat.card H) * (8 * Nat.card K) :=
        mul_le_mul hH' hK' (by positivity) (by positivity)
    _ = 64 * (Nat.card H * Nat.card K) := by ring

end DDNNFNegation
